name: example
description: 'An example of how to use the Marquee widget.'
version: 1.0.0
publish_to: none
repository: https://github.com/marcelgarus/marquee

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  marquee:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
